spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.40.128/sell?characterEncoding=utf-8&useSSL=false
    password: 123456
  jpa:
    show-sql: true
server:
  context-path: /sell
